from __future__ import annotations

import base64
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SIZE = 52
SOURCES = [
    "/assets/images/prof.jpg",
    "/assets/images/1.jpg",
    "/assets/images/2.jpg",
    "/assets/images/3.jpg",
    "/assets/images/4.jpg",
    "/assets/images/5.jpg",
    "/assets/images/6.jpg",
    "/assets/images/7.jpg",
    "/assets/images/8.jpg",
    "/assets/images/9.jpg",
    "/assets/images/10.jpg",
    "/assets/images/1proj.jpg",
    "/assets/images/2proj.jpg",
    "/assets/images/3proj.jpg",
    "/assets/images/4proj.jpg",
    "/assets/images/blog1.jpg",
    "/assets/images/DSC00352.jpg",
    "/assets/images/DSC00359.jpg",
]


def label_from_source(src: str) -> str:
    return Path(src).stem


def fit_with_aspect_ratio(image: Image.Image) -> Image.Image:
    image = image.convert("RGBA")
    scale = SIZE / max(image.width, image.height)
    width = round(image.width * scale)
    height = round(image.height * scale)
    return image.resize((width, height), Image.Resampling.LANCZOS)


def js_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


entries = []
for src in SOURCES:
    image_path = ROOT / src.lstrip("/")
    stamp = fit_with_aspect_ratio(Image.open(image_path)).convert("RGB")
    encoded = base64.b64encode(stamp.tobytes()).decode("ascii")
    entries.append(
        '  { src: "%s", label: "%s", width: %d, height: %d, rgb: "%s" }'
        % (
            js_string(src),
            js_string(label_from_source(src)),
            stamp.width,
            stamp.height,
            encoded,
        )
    )

output = """// Generated by scripts/generate_photo_stamps.py. Do not edit by hand.
const PHOTO_STAMP_DATA = [
%s,
];

export { PHOTO_STAMP_DATA };
""" % ",\n".join(entries)

(ROOT / "js" / "photoStamps.generated.js").write_text(output, encoding="utf-8")
